### ISSUE TITLE
UIP-3198 Add --help flag

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dependency_validator#18]
Running `dependency_validator --help` should print usage info for this command.

Right now, it errors:
```
Unhandled exception:
FormatException: Could not find an option named "help".
#0      Parser.validate (package:args/src/parser.dart:256:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:245:7)
#2      Parser.parse (package:args/src/parser.dart:86:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:133:45)
#4      main (file:///Users/greg.littlefield/.publink/dependency_validator/bin/dependency_validator.dart:32:32)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by evanweible-wf** [comment]
This is already fixed.
